### ISSUE TITLE
[Improvement] Add real 2D support

### ISSUE THREAD

**Issue by Fewnity** [AntonioND/nitro-engine#11]
Hello,
For me the big problem of Nitro Engine is the 2D.
Because if the 2D system we are limited to 30fps in dual screen mode if we just want to use 3D at the top and 2D at the bottom.
Real 2D would allow 60 fps with both screen mode.
You are adding the support of compressed textures, maybe it's time to support real 2D right? :)

Thanks!

**Comment by AntonioND** [comment]
Hi!

Yes, I agree lack of clear guidelines to use 2D graphics is an issue.

To be honest, I'm not sure if adding 2D support to Nitro Engine is a great idea. I was thinking that maybe it would be better if I added a couple of examples combining [NFlib](https://github.com/knightfox75/nds_nflib) or libnds with NE to show how to use 2D graphics. Do you think this would be a good option for you?

Antonio

**Comment by Fewnity** [comment]
Yes a mix of NightFox and NE would be great! I already tried to mix NE and NF but without success I don't know why.
