### ISSUE TITLE
[Improvement] Creating multiple Textures using the same palette

### ISSUE THREAD

**Issue by buchstabenwurst** [AntonioND/nitro-engine#15]
Hello,
I have multiple (most) Textures using the same colors,
it would be nice if there was an option in img2ds to select a Palette.

**Comment by AntonioND** [comment]
I'm deprecating img2ds in favour of grit and ptexconv, so I'm going to close this issue. I still need to update all examples to use grit. ptexconv is already used in the compressed textures example: https://github.com/AntonioND/nitro-engine/blob/1d0b3058aaa309e340f3646393f2077a55e445f1/examples/loading/compressed_texture/assets.sh

**Comment by AntonioND** [comment]
I've started the work here: https://github.com/AntonioND/nitro-engine/commit/c8324ca1b950ae170df48e94a4c3783dfaac5f71

Eventually I will migrate all examples and remove the tool.
