### ISSUE TITLE
ARM9 is compressed to a binary from elf before ndstool?

### ISSUE THREAD

**Issue by lifehackerhansol** [AntonioND/nitro-engine#2]
All source code for examples in Nitro Engine is compressing the elf to binary before using ndstool on it: https://github.com/AntonioND/nitro-engine/blob/38f419d94da7a091e83fa4c2b80a2f10564670ff/examples/other/free_camera/Makefile#L112

Is this intended? Was there a performance benefit to doing so?

This correlates to an issue in TWiLight where none of the Nitro Engine examples were detected in TWiLight as homebrew and was instead detected as a retail title: https://github.com/DS-Homebrew/TWiLightMenu/issues/1753. I removed the `$(TARGET).arm9` flag from here and directly used the `.elf` against ndstool and this was detected fine, but I'm not sure if that would break functionality in Nitro Engine somewhere.

**Comment by lifehackerhansol** [comment]
Resolved by https://github.com/AntonioND/nitro-engine/commit/e98698febf02c30d1daf12d98bde9ade06760ce4.

**Comment by AntonioND** [comment]
Oops, I turned off all notifications in this repository so I didn't see your comments. I only saw the ones in the TWiLightMenu because you mentioned my nickname. Anyway, as mentioned in that thread, I've updated all makefiles so this isn't a problem anymore.
