### ISSUE TITLE
Rich text: NE_RichTextPrioritySet and NE_RichTextPriorityReset are unimplemented

### ISSUE THREAD

**Issue by WiIIiam278** [AntonioND/nitro-engine#28]
Attempting to call [these methods](https://github.com/AntonioND/nitro-engine/blob/ff734036fc3aa1d515a01842b63f7c42a40a3a04/include/NERichText.h#L39-L45) will result in compiler linkage errors as they are not implemented in `NERichText.c`

**Comment by AntonioND** [comment]
Ah, that's a copy-paste error, I started to develop the code of the RichText system with a copy of the previous text system code. They need to be removed. I think it's better to ask the user to set the Z coordinate in every call.

**Comment by AntonioND** [comment]
There: https://github.com/AntonioND/nitro-engine/commit/48ff37231f6ae0a908b93edaea29d7037beebc8b

**Comment by WiIIiam278** [comment]
> Ah, that's a copy-paste error, I started to develop the code of the RichText system with a copy of the previous text system code. They need to be removed. 

No problem! 

> I think it's better to ask the user to set the Z coordinate in every call.

Sounds reasonable &mdash; only thing is, I don't see a way of doing this at the moment? Could be missing something though :)

**Comment by AntonioND** [comment]
Huh, yeah, I got that wrong. Sorry, I thought the functions already took a "depth" argument. Priority functions re-introduced here: https://github.com/AntonioND/nitro-engine/commit/3f3e266a4f2fd2d68daf485d9ca84c21d06e8fd1 I don't want to break code using the functions just to add another argument.
