### ISSUE TITLE
Physics collision boxes can't rotate with object?

### ISSUE THREAD

**Issue by anyzunstudios** [AntonioND/nitro-engine#31]
Hi,
I'm trying to make a simple game where you drive a bus on a small city. The issue comes when you rotate the bus (rectangle), the collision box are still facing at same angle, so they don't rotate alongside the object, so half of the bus can go through obstacles and buildings. I was trying to find out a way to rotate the collision box, but I don't find any rotation method to rotate the X Y Z collision box axes, or at least I don't know how.

Can somebody tell me if it is possible to do and how?

Thanks in advance!

Best regards.

**Comment by AntonioND** [comment]
No, sorry, this isn't supported! The physics engine of NE is very limited, and I personally wouldn't recommend you to use it. I have no plans to improve it because actually getting a good physics engine to work is hard, especially on a platform with a slow CPU like the DS... :(

**Comment by AntonioND** [comment]
I'll star that repo and take a look at it at some point, but I don't want to integrate it here, it would be too complicated.
