### ISSUE TITLE
Can't compile recent versions

### ISSUE THREAD

**Issue by rVicio** [AntonioND/nitro-engine#34]
Hi, I can't compile none of the NE versions since the matrix support for version 0.14, msys2 shows this error:

make -f Makefile.blocksds
make[1]: Entering directory '/opt/devkitpro/nitro-engine'
  CC      source/dsma/dsma.c
make[1]: /opt/wonderful/toolchain/gcc-arm-none-eabi/bin/arm-none-eabi-gcc: No such file or directory
make[1]: *** [Makefile.blocksds:166: build_release/source/dsma/dsma.c.o] Error 127
make[1]: Leaving directory '/opt/devkitpro/nitro-engine'
make: *** [Makefile:16: all] Error 2

It could be something with my devkitpro and devkitarm version but I can still compile previous NE version even 0.14 before the new matrix input suppport.

**Comment by AntonioND** [comment]
You are using the makefile of BlocksDS while using devkitARM. You need to use the ones without ``.blocks``.

**Comment by rVicio** [comment]
Ok, my bad at that, didn't checked the new instructions, it compiled with no problem using the comand "make dkp -j`nproc`", and my projects also compile too.

However, trying compiling the examples, they don't, it states that it cant find the .h files that are creater for the 3d models, for what I can tell, it actually doesn't create them before they are needed.

I'm following the instructions and compiling the examples with the comand "make -f Makefile.dkp".

$ make -f Makefile.dkp
main.c
C:/devkitPro/nitro-engine/examples/loading/assign_transform_matrix/source/main.c:11:10: fatal error:
 sphere_bin.h: No such file or directory
   11 | #include "sphere_bin.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:85: main.o] Error 1
make: *** [Makefile.dkp:163: build] Error 2

**Comment by AntonioND** [comment]
Ah, sorry, that's an actual bug, I haven't actually tested on devkitARM for a while. That makefile needs to be modified so that it says `DATA := data`.

**Comment by AntonioND** [comment]
I've pushed a fix here: https://github.com/AntonioND/nitro-engine/commit/e5ae24567467dffd25ce9e8f8ac9ead94c4660d2 Can you test again?

**Comment by rVicio** [comment]
Yea, it compiles now.

Thanks for the quick reply.

Also, I've checked some of the other examples and they Makefile.dkp also don't specify the DATA path, sorry for the bother.

In any case, I think this issue can be closed.
Happy New year!.

**Comment by AntonioND** [comment]
Ah, you're right... That's annoying, but it had to be fixed: https://github.com/AntonioND/nitro-engine/commit/39117696aac033e6f808e1b3314f3fc7fbc354ff

Thanks for the report! I think this issue can be closed now.
