### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Androxx00** [AntonioND/nitro-engine#35]
Hello, I've been trying to compile the engine but I keep getting this every time:

make[1]: ar: No such file or directory
make[1]: *** [Makefile.blocksds:137: lib/libNE.a] Error 127
make[1]: Leaving directory '/c/dev/src/nitro-engine'
make: *** [Makefile:16: all] Error 2

I've tried reinstalling BlocksDS and devkitPro but that hasn't helped.

**Comment by AntonioND** [comment]
Hmmm it looks like BlocksDS is using an `ar` that comes with the system rather than the one of Wonderful Toolchain, that's why it's failing. I'll push a fix in a minute.

However, if you're using BlocksDS, you could just install the pre-built package with `wf-pacman`: `blocksds-nitroengine`

**Comment by AntonioND** [comment]
It should be fixed now: https://github.com/AntonioND/nitro-engine/commit/459d8f8960acf938d680f8e1de48bd99eb3650df

**Comment by Androxx00** [comment]
That fixed it, thanks!
