### ISSUE TITLE
Any examples for pallets?

### ISSUE THREAD

**Issue by JustMeDaFaq** [AntonioND/nitro-engine#4]
Hi,
are there any examples for how to use pallets?
Like when using RGB256 for textures?

Couldnt find any in the example folders :)

**Comment by JustMeDaFaq** [comment]
NVM, if someone needs:
```
	NE_Palette* palette = NE_PaletteCreate();
	NE_PaletteLoad(palette,(u16 *) Texture256_pal_bin,256,GL_RGB256);
	NE_MaterialTexSetPal(Material,palette);
```

**Comment by AntonioND** [comment]
https://github.com/AntonioND/nitro-engine/tree/5850ae5d5998e08681e1248771f25a775503dab6/examples/loading/paletted_texture

This example should show how that works.
