### ISSUE TITLE
Issues with debugging functions NE_GetPolygonCount, NE_GetVertexCount, NE_GetCPUPercent

### ISSUE THREAD

**Issue by JustMeDaFaq** [AntonioND/nitro-engine#5]
Hi,
im having issues with these three functions:
NE_GetPolygonCount
NE_GetVertexCount
NE_GetCPUPercent

First two always return 0, while the GetCPUPercent one is returning numbrs between 400-600.

I attached an example project and the resulting compiled .nds
[Compiled.zip](https://github.com/AntonioND/nitro-engine/files/8088946/Compiled.zip)
[free_camera.zip](https://github.com/AntonioND/nitro-engine/files/8088942/free_camera.zip)

![Unbenannt](https://user-images.githubusercontent.com/6432949/154491980-18fad9f7-9518-4084-8f78-c34f63d4daeb.png)

**Comment by AntonioND** [comment]
``NE_GetPolygonCount`` and ``NE_GetVertexCount`` don't work on emulators, sorry.

I've checked your code, and ``NE_WaitForVBL(NE_UPDATE_PHYSICS||NE_CAN_SKIP_VBL);`` is wrong (you are using logical or instead of bitwise or). Try with ``NE_WaitForVBL(NE_UPDATE_PHYSICS | NE_CAN_SKIP_VBL);`` and see if that fixes the CPU count.

Also, have you checked on real hardware?

**Comment by JustMeDaFaq** [comment]
NVM, i needed to put those functions after stuff has been drawn. getting polycon and vertex count is now working too :) Sorry for taking up your time and thanks for pointing out || vs | :)

**Comment by AntonioND** [comment]
Yes, you need to call them afterwards.

Also, don't call ``NE_HBLFunc();`` manually, I've just seen you do that before waiting for VBL.

The CPU usage should range from 0 to 100, so there is still something wrong. Can you try without ``NE_CAN_SKIP_VBL``?

**Comment by JustMeDaFaq** [comment]
> Yes, you need to call them afterwards.
> 
> Also, don't call `NE_HBLFunc();` manually, I've just seen you do that before waiting for VBL.
> 
> The CPU usage should range from 0 to 100, so there is still something wrong. Can you try without `NE_CAN_SKIP_VBL`?

Its still giving me 400-600 percent.
printf("\nCpuInPercentCPU %i",NE_GetCPUPercent());

Thats with NE_HBLFunc(); commented out @AntonioND

**Comment by JustMeDaFaq** [comment]
Also doing:
`printf("\nTexMemory %03d",NE_TextureFreeMemPercent());`

Always returns 0. Tested on both, emulator and device. Same goes for `NE_TextureFreeMem`

**Comment by AntonioND** [comment]
Oh, yeah, the mem free functions are broken, sorry. I will take a look at the CPU usage issue...

**Comment by JustMeDaFaq** [comment]
I have NE_TextureFreeMem working. Only issue is the CPU in percent know, which seems to show me correct numbersif i format it like printf("\nTexMemory %03d",NE_TextureFreeMemPercent()); tho.

**Comment by AntonioND** [comment]
Oooh so the CPU usage function works, it's just that you're not wearing what was printed before. If you print 100 one frame, and 4 the following one, you'll get 400 unless you erase the zeroes.

**Comment by JustMeDaFaq** [comment]
Thanks, got it all working :)
