### ISSUE TITLE
Dual Mode, bank C and D

### ISSUE THREAD

**Issue by JustMeDaFaq** [AntonioND/nitro-engine#7]
Hi, 
im sorry! In Dual mode, bank C and D cant be used. What are they used for?
If i understand correctly, i cant use them to store textures for the bottom screens ui?

**Comment by AntonioND** [comment]
The NDS can't render 3D to both screens at the same time. To get it working, you need to capture the 3D output and store it somewhere. Essentially, when you draw screen A you capture it and you're showing the previous captured image from screen B, and then you switch and show the captured screen A while capturing screen B. Banks C and D are the ones that store the saved images.

**Comment by JustMeDaFaq** [comment]
Didnt received a notification. Thanks alot, im storing a basic looking gui now in banks H and I using native background and OAM api. (i hate OAM lol) So i have the main banks left for Textures. Thanks for the explanation!
